#!/bin/zsh

# TODO this cleanup / term logic might be better in the common reg-api
local -a links=("${(ps|:|)1}")
local -a pids
local link
for link in "$links[@]"; do
    if [[ -n "$link" ]]; then
        reg -bb -I "$link" unlink "$REG_SOCKET"
    fi
done

command-server-terminate "$REG_SOCKET"
